# Site settings
title: Nikhil Kumar
description: PhD Candidate in Public Policy (Economics track) at Harvard University
baseurl: "" # subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Author information
author:
  name: Nikhil Kumar
  email: nikhil_kumar1@g.harvard.edu

# Build settings
markdown: kramdown
highlighter: rouge

# Theme (using GitHub Pages supported theme)
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
